before_install:
  - sudo apt-get update
  - sudo apt-get install -y ocaml-findlib
install:
  - bash -ex .travis-ocaml.sh
  - opam install -y oasis ocamlfind
sudo: required
script: which ocamlfind; ocamlfind list ; make
env:
  - OCAML_VERSION=4.04
    #addons:
    #apt:
    #packages:
    #  - ocaml-findlib
