before_install:
  - sudo apt-get update
  - sudo apt-get install -y ocaml-findlib
install:
  - bash -ex .travis-ocaml.sh
  - opam install -y oasis ocamlfind
sudo: required
script: echo $PATH; ls /home/travis/.opam/; ls /home/travis/.opam/4.04.2/bin ; make
env:
  - OCAML_VERSION=4.04
    #addons:
    #apt:
    #packages:
    #  - ocaml-findlib
